-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 11:24:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Товары`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Товары` (
  `id_товара` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `цена` DECIMAL(10,2) NOT NULL,
  `остаток` INT NOT NULL DEFAULT 0,
  `описание` TEXT NULL,
  PRIMARY KEY (`id_товара`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Категории`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Категории` (
  `id_категории` INT NOT NULL AUTO_INCREMENT,
  `название` VARCHAR(100) NOT NULL,
  `родительская_категория` INT NULL,
  PRIMARY KEY (`id_категории`),
  INDEX `idx_родительская_категория` (`родительская_категория` ASC) VISIBLE,
  CONSTRAINT `fk_категории_родитель`
    FOREIGN KEY (`родительская_категория`)
    REFERENCES `mydb`.`Категории` (`id_категории`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Товары_категории`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Товары_категории` (
  `id_товара` INT NOT NULL,
  `id_категории` INT NOT NULL,
  PRIMARY KEY (`id_товара`, `id_категории`),
  INDEX `idx_товары_категории_категория` (`id_категории` ASC) VISIBLE,
  CONSTRAINT `fk_товары_категории_товар`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_товары_категории_категория`
    FOREIGN KEY (`id_категории`)
    REFERENCES `mydb`.`Категории` (`id_категории`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Покупатели`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Покупатели` (
  `id_покупателя` INT NOT NULL AUTO_INCREMENT,
  `логин` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `телефон` VARCHAR(20) NULL,
  `адрес` VARCHAR(200) NULL,
  PRIMARY KEY (`id_покупателя`),
  UNIQUE INDEX `логин_UNIQUE` (`логин` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Заказы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Заказы` (
  `id_заказа` INT NOT NULL AUTO_INCREMENT,
  `дата` DATETIME NOT NULL,
  `статус` VARCHAR(20) NULL,
  `сумма` DECIMAL(12,2) NULL,
  `id_покупателя` INT NULL,
  PRIMARY KEY (`id_заказа`),
  INDEX `idx_заказы_покупатель` (`id_покупателя` ASC) VISIBLE,
  CONSTRAINT `fk_заказы_покупатель`
    FOREIGN KEY (`id_покупателя`)
    REFERENCES `mydb`.`Покупатели` (`id_покупателя`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Состав_заказа`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Состав_заказа` (
  `id_заказа` INT NOT NULL,
  `id_товара` INT NOT NULL,
  `количество` INT NOT NULL,
  `цена_на_момент` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id_заказа`, `id_товара`),
  INDEX `idx_состав_заказа_товар` (`id_товара` ASC) VISIBLE,
  CONSTRAINT `fk_состав_заказа_заказ`
    FOREIGN KEY (`id_заказа`)
    REFERENCES `mydb`.`Заказы` (`id_заказа`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_состав_заказа_товар`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Отзывы`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Отзывы` (
  `id_отзыва` INT NOT NULL AUTO_INCREMENT,
  `текст` TEXT NULL,
  `оценка` INT NULL,
  `дата` DATE NULL,
  `id_товара` INT NOT NULL,
  `id_покупателя` INT NOT NULL,
  PRIMARY KEY (`id_отзыва`),
  INDEX `idx_отзывы_товар` (`id_товара` ASC) VISIBLE,
  INDEX `idx_отзывы_покупатель` (`id_покупателя` ASC) VISIBLE,
  CONSTRAINT `fk_отзывы_товар`
    FOREIGN KEY (`id_товара`)
    REFERENCES `mydb`.`Товары` (`id_товара`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_отзывы_покупатель`
    FOREIGN KEY (`id_покупателя`)
    REFERENCES `mydb`.`Покупатели` (`id_покупателя`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `chk_оценка` CHECK (`оценка` BETWEEN 1 AND 5))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;