
from .entities import Account, Transaction

from typing import Protocol, List

class AccountRepository(Protocol):
    """Интерфейс репозитория для работы со счетами."""
    def get_by_id(self, account_id: int) -> Account: ...
    def get_by_number(self, number: str) -> Account: ...
    def create(self, account: Account) -> Account: ...
    def update(self, account: Account) -> None: ...

class TransactionRepository(Protocol):
    """Интерфейс репозитория для работы с транзакциями."""
    def create(self, transaction: Transaction) -> Transaction: ...
    def find_by_account_id(self, account_id: int) -> List[Transaction]: ...